@url =http://localhost:3000

GET {{url}}

###

POST {{url}}/register
Content-Type: application/json

{
    "name": "Raman",
    "email": "raman@yopmail.com",
    "password": "12345678"
}


###

POST {{url}}/login
Content-Type: application/json

{
   "email": "raman@yopmail.com",
   "password": "12345678"
}

###
GET {{url}}/check-in/status
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NzI1MDQxMzcsInVzZXJJZCI6MSwiaWF0IjoxNjcyNDc4OTM3fQ.dfs3Z6cQPkwEIcqH_ljbbqyBIXt20NrhvhY2E_u6cE8

###
POST {{url}}/check-in/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NzI1MDQxMzcsInVzZXJJZCI6MSwiaWF0IjoxNjcyNDc4OTM3fQ.dfs3Z6cQPkwEIcqH_ljbbqyBIXt20NrhvhY2E_u6cE8

###
POST {{url}}/leaveForm
Content-Type: application/json

{
    "date": "12-25-11",
    "absence_from": "",
    "absence_through": "",
    "total_days": "",
    "type_of_leave": "",
    "reason_for_leave": "",
}