@url =http://localhost:3000

GET {{url}}

###

POST {{url}}/register
Content-Type: application/json

{
    "name": "Raman",
    "email": "raman@yopmail.com",
    "password": "12345678"
}


###

POST {{url}}/login
Content-Type: application/json

{
   "email": "raman@yopmail.com",
   "password": "12345678"
}

###
GET {{url}}/check-in/status
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NzI1Nzg2NDYsInVzZXJJZCI6MSwiaWF0IjoxNjcyNTUzNDQ2fQ.rCfc_kc0LHJyW50DfUxXT9EZ9fEvXelfDp_oyfbHCkU
###
POST {{url}}/check-in/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NzI1Nzg2NDYsInVzZXJJZCI6MSwiaWF0IjoxNjcyNTUzNDQ2fQ.rCfc_kc0LHJyW50DfUxXT9EZ9fEvXelfDp_oyfbHCkU

###
POST {{url}}/leave-form
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NzI1Nzg2NDYsInVzZXJJZCI6MSwiaWF0IjoxNjcyNTUzNDQ2fQ.rCfc_kc0LHJyW50DfUxXT9EZ9fEvXelfDp_oyfbHCkU

{
    "date": "12-25-11",
    "absence_from": "12-02-23",
    "absence_through": "10-4-2022",
    "total_days": "4",
    "type_of_leave": "medical",
    "reason_for_leave": "medical emergancy"
}